import { chromium } from "playwright";
const shotDir = "C:/Users/yucel/AppData/Local/Temp/claude/c--Users-yucel-Desktop-formen-takip/ebd5c088-c4c2-4f43-923d-ff14bfbaf1c5/scratchpad";
const BASE = "http://localhost:8080";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 1400 } });
await page.goto(`${BASE}/login`, { waitUntil: "networkidle" });
await page.fill('input[type="email"]', "genel.mudur@formen-demo.com");
await page.fill('input[type="password"]', "Demo!2026");
await page.click('button[type="submit"]');
await page.waitForSelector("text=Genel Bakış", { timeout: 15000 });
await page.evaluate(() => localStorage.setItem("formen_theme", "light"));
await page.click("text=Tespitler");
await page.waitForSelector("text=Toplam Aktif Tespit", { timeout: 10000 });
await page.reload({ waitUntil: "networkidle" });
await page.waitForTimeout(500);
await page.locator("table tbody tr").first().click();
await page.waitForSelector("text=Neden Bu Tespit Oluştu?", { timeout: 10000 });
await page.waitForTimeout(1000);
await page.screenshot({ path: `${shotDir}/anomaly-detail-light2.png`, fullPage: true });
await browser.close();
